### ISSUE TITLE
Add Watchlist Functionality

### ISSUE THREAD

**Issue by jensenkd** [jensenkd/plex-api#64]
Plex has recently added WatchList as a feature to the server platform.  

I'd like to implement the following:

GetWatchlists - Returns list of Movie and Show items that are in a user's watchlist.

IsOnWatchlist - Returns true if the item is on the user's watchlist

AddToWatchlist - Add media item to user's watchlist

RemoveFromWatchlist - Remove media item from user's watchlist

Watchlist capability is stored on Plex.tv and accessible via: 'https://metadata.provider.plex.tv'

**Comment by seertenedos** [comment]
i was just about to open an issue to ask about support for https://metadata.provider.plex.tv/
specifically supporting looking up the plex guid to get the info on an item. 
example "plex://episode/62471ee353143040cc2acbf6" = https://metadata.provider.plex.tv/library/metadata/62471ee353143040cc2acbf6?X-Plex-Token=xxxxx

i found a need for this because the same plex episode over servers can have different plex guid as it seems they sometimes map to imdb, tvdb or tmdb and in some cases that gets split over 2 or more guids.

Would that be possible to add if you are already adding metadata.provider.plex.tv?

**Comment by seertenedos** [comment]
Actually i likely will not need the metadata.provider.plex.tv as i just worked out it was a settting missing that was causing the info to not come back on seasons and episodes so raised a pull request to fix it

**Comment by jensenkd** [comment]
Watchlist Functionality has been added.
